In [1]:
def funcion():
  print('Hola,buenos dias')


In [2]:
funcion()

Hola,buenos dias


In [3]:
def saludar(nombre):
  print(f'hola buenos dias {nombre}')

In [4]:
saludar('Roberto')

hola buenos dias Roberto


In [5]:
def sumar(num1,num2):
  resultado=num1+num2
  return resultado

In [6]:
sumar(2,3)

5

Funcion MAP

In [8]:
def multiplicar(numero):
  return numero*2

In [9]:
multiplicar(5)

10

In [11]:
lista=[1,2,3,4,5]
lista2=list(map(multiplicar,lista))

In [12]:
lista2

[2, 4, 6, 8, 10]

Funcion Lambda

In [13]:
def multiplicar(numero):
  return numero*2

In [14]:
multiplicar(5)

10

In [15]:
lista1=[1,2,3,4]
lista2=list(map(multiplicar,lista1))
lista2

[2, 4, 6, 8]

In [16]:
lista3=list(map(lambda numero:numero*2,lista1))
lista3

[2, 4, 6, 8]

FILTRAR

In [17]:
def par(numero):
  if numero%2==0:
    return True
  else:
    return False

In [18]:
par(3)

False

In [19]:
lista23=[1,2,3,4,5,6,7]
lista_pares=list(filter(par,lista23))
lista_pares

[2, 4, 6]

In [20]:
lista23=[1,2,3,4,5,6,7]
lista_pares1=list(filter(lambda numero:numero%2==0,lista23))
lista_pares1

[2, 4, 6]

In [23]:
frase='hola, este es un curso basico de python'

In [24]:
palabra=frase.split()
palabra

['hola,', 'este', 'es', 'un', 'curso', 'basico', 'de', 'python']

In [25]:
suma=0
for letra in palabra:
  suma=suma+1
print(suma)

8


In [26]:
lista_1=[1,-1,4,-15,9,7,6,-3,2,-20]
def positivo(numero):
  if numero>0:
    return True
  else:
    return False
lista2=list(filter(lambda numero:numero>0,lista_1))
lista2

[1, 4, 9, 7, 6, 2]

In [40]:
lista_frutas=["manzana","platano","melocoton","pera","limon","platano","naranja"]
def repetido(lista):
  i=1
  lista_sin_repetir=[]
  while(i<len(lista)):
    if lista[i]==lista[i-1]:
      lista_sin_repetir.append(lista[i])
    i=i+1
  return lista_sin_repetir

In [39]:
repetido(lista_frutas)

[]

In [48]:
lista_frutas=["manzana","platano","melocoton","pera","limon","platano","naranja"]
def repetido(lista):
  lista_sin_repetir = []
  elementos_vistos = set()  # Usamos un conjunto para rastrear elementos únicos
  for fruta in lista:
    if fruta not in elementos_vistos:
      lista_sin_repetir.append(fruta)
      elementos_vistos.add(fruta)
  return lista_sin_repetir

print(repetido(lista_frutas))

['manzana', 'platano', 'melocoton', 'pera', 'limon', 'naranja']


In [49]:
import numpy as np

In [50]:
lista=[1,2,3,4]

In [51]:
array=np.array(lista)
array

array([1, 2, 3, 4])

In [52]:
lista2=[[1,2,3],[4,5,6],[7,8,9]]
lista2

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [53]:
array2=np.array(lista2)
array2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

funciones arange,zeros,one,linspace,eye

In [54]:
array=np.arange(5)
# te crea un array con valores de secuencia desde el 0 al 4
array

array([0, 1, 2, 3, 4])

In [55]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])