<a href="https://colab.research.google.com/github/robert2999/machine_learning/blob/main/numpy1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

NUMPY arrays ,orange,zeros,ones,linspace,eye

In [1]:
import numpy as np

In [3]:
array=np.arange(5)
array

array([0, 1, 2, 3, 4])

In [7]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(2,10,2)

array([2, 4, 6, 8])

In [9]:
np.arange(2,20,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [10]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [11]:
np.zeros(3)

array([0., 0., 0.])

In [13]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [14]:
np.ones(4)

array([1., 1., 1., 1.])

In [15]:
np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [17]:
np.linspace(5,10,30)

array([ 5.        ,  5.17241379,  5.34482759,  5.51724138,  5.68965517,
        5.86206897,  6.03448276,  6.20689655,  6.37931034,  6.55172414,
        6.72413793,  6.89655172,  7.06896552,  7.24137931,  7.4137931 ,
        7.5862069 ,  7.75862069,  7.93103448,  8.10344828,  8.27586207,
        8.44827586,  8.62068966,  8.79310345,  8.96551724,  9.13793103,
        9.31034483,  9.48275862,  9.65517241,  9.82758621, 10.        ])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

Numeros aleatorios-rand y randn

In [19]:
np.random.rand(5)

array([0.32001452, 0.47040303, 0.27450264, 0.7874419 , 0.91074128])

In [21]:
np.random.rand(2,5)

array([[0.12514099, 0.65070467, 0.58846515, 0.80772294, 0.86324422],
       [0.10014611, 0.48976819, 0.03407833, 0.95375277, 0.29687296]])

In [22]:
np.random.randn(4)

array([ 2.07767942, -0.37077099, -0.85630131, -1.53031474])

In [23]:
np.random.randn(2,4)

array([[ 0.2876877 ,  1.20888462,  0.34460583, -0.70988172],
       [ 1.83772544,  0.47492513, -1.20578634,  0.42654844]])

In [28]:
np.random.randint(1,20)

7

In [29]:
np.random.randint(1,20,10)

array([ 7,  3,  7, 12,  9, 11,  9, 18, 10, 16])

numpy array -reshape (cambio de filas y columnas)

In [30]:
array=np.random.randint(1,100,25)
array

array([16, 11, 13, 66, 44,  4, 68, 34, 87, 70, 11,  8, 84,  8, 64, 74, 41,
       66, 75, 36, 73,  8, 55, 31,  2])

In [31]:
# cabe resaltar que el numero de filas x columnas debe darte la
#longitud del array en el caso anterior es 25
matriz=array.reshape(5,5)
matriz

array([[16, 11, 13, 66, 44],
       [ 4, 68, 34, 87, 70],
       [11,  8, 84,  8, 64],
       [74, 41, 66, 75, 36],
       [73,  8, 55, 31,  2]])

VALOR MAXIMO Y VALOR MINIMO max y min

In [32]:
array=np.random.randint(1,100,50)
array

array([33, 33, 48, 39, 45, 23, 41, 66, 69, 48, 58, 59, 25, 65, 85, 78, 54,
       86, 45, 50, 78, 12, 12, 59, 86,  4,  7, 55,  1,  3, 29, 96, 78, 93,
       61, 31, 50, 45,  5, 94, 26, 42, 30, 90, 60, 88, 60, 39, 44, 93])

In [35]:
valor_maximo=array.max()
valor_maximo

np.int64(96)

In [36]:
posicion=array.argmax()
posicion

np.int64(31)

In [39]:
valor_min=array.min()
valor_min

np.int64(1)

In [40]:
pos_min=array.argmin()
pos_min


np.int64(28)